image: docker:19.03.10

services:
  - docker:dind

variables:
  ECR_REGISTRY: 067783583101.dkr.ecr.ap-southeast-1.amazonaws.com/qeoqeo-be-lar
  TASK_DEFINITION_NAME: qeoqeo-be-lar-task-definition
  CLUSTER_NAME: qeoqeo-be-lar-cluster
  SERVICE_NAME: qeoqeo-be-lar-service
  IMAGE_TAG: main

before_script:
  - apk add --no-cache curl jq python py-pip
  - pip install awscli
  - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
  - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
  - aws configure set region $AWS_DEFAULT_REGION
  - $(aws ecr get-login --no-include-email --region "${AWS_DEFAULT_REGION}")

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - echo "Building image..."
    - docker build -f docker/ecs/Dockerfile -t $ECR_REGISTRY:$IMAGE_TAG .
    - echo "Pushing image..."
    - docker push $ECR_REGISTRY:$IMAGE_TAG
  only:
    - main

deploy:
  stage: deploy
  script:
    - echo "Updating the service..."
    - aws ecs update-service --region "${AWS_DEFAULT_REGION}" --cluster "${CLUSTER_NAME}" --service "${SERVICE_NAME}" --task-definition "${TASK_DEFINITION_NAME}"
  only:
    - main
